// register new user
export const LOADING_USER_DATABASE = 'LOADING_USER_DATABASE'
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS'
export const USER_CREATED_FAIL = 'USER_CREATED_FAIL'
// user log in
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
// user log out
export const USER_LOG_OUT = 'USER_LOG_OUT'
// profile
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const PROFILE_FOUND = 'PROFILE_FOUND'
export const PROFILE_CLEAR = 'PROFILE_CLEAR'
// create profile
export const PROFILE_CREATING = 'PROFILE_CREATING'
export const PROFILE_CREATING_SUCCESS = 'PROFILE_CREATING_SUCESS'
export const PROFILE_CREATING_FAIL = 'PROFILE_CREATING_FAIL'

