export const LOADING_USER_DATABASE = 'LOADING_USER_DATABASE'
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS'
export const USER_CREATED_FAIL = 'USER_CREATED_FAIL'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOG_OUT = 'USER_LOG_OUT'
